# Site settings
title: e-curieux.com
email: contact@e-curieux.com
description:  Ce blog est utilisé pour suivre mes projets en cours
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://e-curieux.com" # the base hostname & protocol for your site
twitter_username: e-curieux
github_username:  e-curieux

# Build settings
markdown: kramdown
